// Code generated by goctl. DO NOT EDIT.
// Source: reply.proto

package server

import (
	"context"

	"gozero/application/reply/rpc/internal/logic"
	"gozero/application/reply/rpc/internal/svc"
	"gozero/application/reply/rpc/service"
)

type ReplyServer struct {
	svcCtx *svc.ServiceContext
	service.UnimplementedReplyServer
}

func NewReplyServer(svcCtx *svc.ServiceContext) *ReplyServer {
	return &ReplyServer{
		svcCtx: svcCtx,
	}
}

func (s *ReplyServer) PostReply(ctx context.Context, in *service.PostReplyRequest) (*service.Response, error) {
	l := logic.NewPostReplyLogic(ctx, s.svcCtx)
	return l.PostReply(in)
}

func (s *ReplyServer) DeleteReply(ctx context.Context, in *service.DeleteReplyRequest) (*service.Response, error) {
	l := logic.NewDeleteReplyLogic(ctx, s.svcCtx)
	return l.DeleteReply(in)
}

func (s *ReplyServer) UpdateReply(ctx context.Context, in *service.UpdateReplyRequest) (*service.Response, error) {
	l := logic.NewUpdateReplyLogic(ctx, s.svcCtx)
	return l.UpdateReply(in)
}

func (s *ReplyServer) GetReply(ctx context.Context, in *service.GetReplyRequest) (*service.GetReplyResponse, error) {
	l := logic.NewGetReplyLogic(ctx, s.svcCtx)
	return l.GetReply(in)
}
